name: Run SQL Script on SQL Server

on:
  push:
    branches: dev
  workflow_dispatch:

jobs:
  run-sql:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SQL Server Command-Line Tools
      run: |
        curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
        curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
        sudo apt-get update
        sudo ACCEPT_EULA=Y apt-get install -y mssql-tools unixodbc-dev

    - name: Run SQL scripts
      shell: bash
      run: |
        for file in ./sql/*.sql; do
          echo "Running $file..."
          /opt/mssql-tools/bin/sqlcmd \
            -S tcp:192.168.1.34,1433 \
            -U sa \
            -P 2207 \
            -i "$file"
        done

