name: Run SQL Script on SQL Server (Self-Hosted)

on:
  push:
    branches: dev
  workflow_dispatch:

jobs:
  run-sql:
    runs-on: self-hosted  # This will use the runner installed on your local machine

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run SQL scripts using sqlcmd
      shell: powershell
      run: |
        $sqlFiles = "E:\Database versioning using github actions\DB-migrations\sql\customer_table.sql"
        Get-ChildItem -Path ".\sql\" -Filter *.sql | ForEach-Object {
          Write-Host "Running $($_.FullName)..."
          sqlcmd -S localhost -U sa -P 2207 -i $sqlFiles
